name: 'Provides CERNs ROOT'
description: 'Installs and loads ROOT in given version'

inputs:
  version:
    description: 'The ROOT version'
    required: false
    default: 'latest'
  os:
    description: 'The Runner OS'
    required: false
    default: 'ubuntu-latest'

outputs:
  rootsys:
    description: "ROOTSYS value"
    value: ${{ steps.provide-root.outputs.rootsys }}

runs:
  using: "composite"
  steps: 
    - name: Install root
      id: provide-root
      shell: bash
      run: |
        echo "Install root-${{ inputs.version }} on ${{ runner.os }} at ${{ inputs.os }}"
        ${GITHUB_ACTION_PATH}/script.sh "${{ runner.os }}" "${{ inputs.os }}" "${{ inputs.version }}"
