# This is an example of using Composite Run Steps Actions
name: provide-cern-root Composite Example

on: [workflow_dispatch]

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-20.04 ]
        version: [ 6.26.14, 6.28.10, 6.30.02 ]
    name: Get CERNs ROOT example
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - id: root
        uses: rlalik/provide-cern-root@v2
        with:
          version: ${{ matrix.version }}
          os: ${{ matrix.os }}
      - run: |
          export ROOTSYS=${{ steps.root.outputs.rootsys }}
          echo ROOTSYS=$ROOTSYS
          . ${ROOTSYS}/bin/thisroot.sh
          root-config --version
        shell: bash
